### ISSUE TITLE
When have a default value and input some numbers.

### ISSUE THREAD

**Issue by Moln** [leo/args#118] opened 2018-02-08 09:36 UTC
https://github.com/leo/args/blob/f19c7e3cdfe8c75813597c262d1516c740213840/lib/utils.js#L54-L59

There's a problem here. When an argument has a default value and input some numbers.

### Test code

```js
//test.js
var args = require('args');
args.option('name', 'Input alnum.', 'guest');
const flags = args.parse(process.argv);

console.log(flags);
```

```bash
> node test.js -n 123123
```

### Expected results

```
{ n: '123123', name: '123123' }
```

### Actual results

```
{ n: 'guest', name: 'guest' }
```

**Comment by ntwcklng** [comment] 2018-02-08 18:41
Hey @Moln i think this is a duplicate of #115 - try this:

```js
const flags = args.parse(process.argv, {
  mri: {
    string: 'n'
  }
})
```

**Closed by ntwcklng** 2018-02-08 18:41 UTC
