### ISSUE TITLE
Impossible to pass strings args with numeric values

### ISSUE THREAD

**Issue by michaelmruta** [leo/args#125] opened 2018-06-03 03:02 UTC
0xb9770c5a becomes 3111586908
000000003426e209 becomes 3.426e+212
etc.

**Comment by ntwcklng** [comment] 2018-06-03 08:30
Hey @michaelmruta i think this is a duplicate of #115. Can you try to specify the option or command in the `mri` oder `minimist` options as a string?

**Closed by ntwcklng** 2018-06-03 08:30 UTC
