### ISSUE TITLE
Process.exit() in help

### ISSUE THREAD

**Issue by krigton** [leo/args#23] opened 2016-06-29 17:55 UTC
The showHelp will not console.log bigger helps due to the process.exit(). I think using process.exitCode or no exit at all would be better, and let the users to handle their exit on help. 

thanks

**Comment by leo** [comment] 2016-07-02 13:31
Technically, there probably won't be a way around exiting. Because otherwise, the rest of the binary would simply be executed. That means, the code will throw errors, output messages and other things AFTER the help was outputted.

I think the reason why this bug occurs is because a tiny part of the method that outputs the usage information is async. So we should be able to fix this by making it completely sync. This way, all details would be outputted before the process gets exited...

Also: How does setting `process.exitCode` before doing `process.exit()` make sure that everything gets outputted before the process gets exited? 😊 As far as I know, it just tells the system whether the process should exit with an error or not.

**Comment by krigton** [comment] 2016-07-02 13:34
yes you are right

Sent from Yahoo Mail on Android 
 
  On Sat, 2 Jul, 2016 at 16:31, Leo Lamprecht<notifications@github.com> wrote:   
Technically, there probably won't be a way around exiting. Because otherwise, the rest of the binary would simply be executed. That means, the code will throw errors, output messages and other things AFTER the help was outputted.

I think the reason why this bug occurs is because a tiny part of the method that outputs the usage information is async. So we should be able to fix this by making it completely sync. This way, all details would be outputted before the process gets exited...

Also: How does setting process.exitCode before doing process.exit() make sure that everything gets outputted before the process gets exited? 😊 As far as I know, it just tells the system whether the process should exit with an error or not.

**Comment by leo** [comment] 2016-07-03 14:07
Weird. I'm not able to fully reproduce this. I saw it happening once, but I don't know what created the error. It looks like the whole method that handles this is completely synchronous. Any ideas?

**Comment by leo** [comment] 2016-07-13 09:00
Closing this now since I haven't managed to reproduce it. It might also be fixed now because the child process isn't detached anymore (might be related to that).

**Closed by leo** 2016-07-13 09:00 UTC
Labels: invalid, patch
