### ISSUE TITLE
Args is not correctly parsed when init is specified

### ISSUE THREAD

**Issue by whitejava** [leo/args#119] opened 2018-02-15 11:41 UTC
Version is 3.0.8. As described by unit test:

``` js
import argParser from 'args';
import chai from 'chai';
const expect = chai.expect;

argParser.option('arg1', 'foo', undefined, (x)=>x);
argParser.option('arg2', 'bar', 'a', (x)=>x);

describe('args bug', function() {
    it('arg1 should be string when specified to a number', function() {
        let result = argParser.parse(['node','/file','--arg1','123']);
        expect(result).to.have.property('arg1', '123'); // but is 123
    })

    it('arg1 should be string when specified to a string', function() {
        let result = argParser.parse(['node','/file','--arg1','abc']);
        expect(result).to.have.property('arg1', 'abc'); // it is ok
    })

    it('arg2 should be string when specified to a number', function() {
        let result = argParser.parse(['node','/file','--arg2','123']);
        expect(result).to.have.property('arg2', '123'); // but is a
    })

    it('arg2 should be string when specified to a number', function() {
        let result = argParser.parse(['node','/file','--arg2','abc']);
        expect(result).to.have.property('arg2', 'abc'); // it's ok
    })
})
```

**Comment by whitejava** [comment] 2018-02-15 11:41
version is 3.0.8

**Comment by ntwcklng** [comment] 2018-02-15 16:28
Duplicate of #115 #118
Please specify what `type` you expect:

```js
describe('args bug', function() {
  it('arg1 should be string when specified to a number', function() {
    let result = argParser.parse(['node', '/file', '--arg1', '123'], {
      mri: { string: 'arg1' } // mri options
    })
    expect(result).to.have.property('arg1', '123') // but is 123
  })

  it('arg1 should be string when specified to a string', function() {
    let result = argParser.parse(['node', '/file', '--arg1', 'abc'])
    expect(result).to.have.property('arg1', 'abc')
  })

  it('arg2 should be string when specified to a number', function() {
    let result = argParser.parse(['node', '/file', '--arg2', '123'], {
      mri: { string: 'arg2' } // mri options
    })
    expect(result).to.have.property('arg2', '123')
  })

  it('arg2 should be string when specified to a number', function() {
    let result = argParser.parse(['node', '/file', '--arg2', 'abc'])
    expect(result).to.have.property('arg2', 'abc')
  })
})
```

**Closed by ntwcklng** 2018-02-15 16:28 UTC
